### ISSUE TITLE
cannot import usb.core with python3

### ISSUE THREAD

**Issue by outtacontrol216** [respeaker/pixel_ring#3]
so i can`t use it with google assistant
any suggestions?

**Comment by xiongyihui** [comment]
How did you install the package?
I tried to run `sudo pip3 install pixel_ring`, there is no problem.

![image](https://user-images.githubusercontent.com/948283/36764468-bcccf540-1c67-11e8-9196-7980a5bf58e2.png)

BTW, `usb.core` is from the pyusb package which is one of the pixel_ring's dependencies

**Comment by outtacontrol216** [comment]
my mistake. thank you for testing it. i just forgot to install to virtual env. works really well with my respeaker 4mic :)
